apiVersion: v1
kind: Service
metadata:
  name: churnshield-service
spec:
  selector:
    app: churnshield-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
      nodePort: 30080
  type: NodePort